# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 234ecca7539c5f61e3de9fc466d588108e23cc948cfa470035f7097064bb3d861a70eba326f5f9746c2287efc1be322c661a85bc0bbf1a65842a247e48642e67

test:
  secret_key_base: ac16b7b0e8acf5d6d61c03e8fbaacffdb79d39a0088d2601d2ce49294d816069c88b6fca154fafb9a8a5c78449d947af400c01c52ffd524005c9f574113ca52a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
